lab/admin_ac/urls.py
from django.conf.urls import include, url
import admin_ac.views as views


urlpatterns = [

    url(r'^$', views.login),
    url(r'^user/', views.page),
    url(r'^event/$', views.events),
    url(r'^event/create/', views.create_event),
    url(r'^event/del_event/(?P<id>[0-9]+)', views.deleting_event),
    url(r'^club/', views.club),
    url(r'^logs/', views.logs),
    url(r'^match/', views.match),
    url(r'^logout/', views.logout),
    url(r'^userprop/(?P<id>[0-9]+)', views.user_spec),
    url(r'^del/user/(?P<id>[0-9]+)',views.del_user),
    url(r'^locks/user/(?P<id>[0-9]+)',views.locks_user),
    url(r'^unlocks/user/(?P<id>[0-9]+)',views.unlocks_user),
    url(r'^create_club/', views.create_club),
    url(r'^del_club/(?P<id>[0-9]+)', views.del_club),
    url(r'^match_create/', views.match_create),
    url(r'^match_spec/(?P<id>[0-9]+)',views.match_spec),
    url(r'^del_match/(?P<id>[0-9]+)',views.match_del),
    url(r'^bets/',views.bets),
]

lab/lab/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
import lab.views as views

urlpatterns = [
    url(r'^accaunt/', include('acaunt.urls')),
    url(r'^$', views.index ),
    url(r'^rate/(?P<id_match>[0-9]+)/', views.rate),
    url(r'^admin/', include('admin_ac.urls')),
    url(r'^bet_put/(?P<id_match>[0-9]+)',views.bet_put),
]

lab/admin_ac/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

lab/admin_ac/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget

import admin_ac.admin_conector as admin_conector

def choice_club():
    clubs = admin_conector.get_all_club()
    return ((i[0],i[1]) for i in clubs)


def choices_match():
    matches = admin_conector.get_all_match()
    choices = []
    for m in matches:
        match_str = '{0} - {1}'.format(m['name_club1'], m['name_club2'])
        choices.append( ( m['id_match'], match_str ) )
    return choices


class MatchCreate(forms.Form):
    club_1 = forms.ChoiceField(choices=choice_club)
    club_2 = forms.ChoiceField(choices=choice_club)
    date = forms.DateField()


class MatchEdit(forms.Form):
    club_1 = forms.ChoiceField(choices=choice_club)
    club_2 = forms.ChoiceField(choices=choice_club)
    date = forms.DateField()
    gool_club_1 = forms.IntegerField(required=False)
    gool_club_2 = forms.IntegerField(required=False)


class SearchForm(forms.Form):
    date = forms.DateField(required=False)
    date_max = forms.DateField(required=False)
    money_min = forms.IntegerField(required=False)
    money_max = forms.IntegerField(required=False)


class EventCreate(forms.Form):
    match_id = forms.ChoiceField(choices=choices_match)
    coeff_win_first = forms.DecimalField(label='First Win')
    coeff_draw = forms.DecimalField(label='Draw')
    coeff_win_second = forms.DecimalField(label='Second Win')

lab/admin_ac/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

import acaunt.forms as forms
import acaunt.user_db_conect as user_db_conect
import acaunt.log_money as log_money
import log_conector
import admin_ac.admin_conector as admin_conector
import admin_ac.forms as admin_forms



def login(request):
    if request.method == 'GET':
        if 'admin_user_id' in request.session:
            return HttpResponseRedirect('/admin/user/')
        form = forms.LoginForm
        return render(request, 'admin_ac/login.html', {'form': form ,})
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = user_db_conect.authenticate(form.cleaned_data['username'],
                                               form.cleaned_data['password'])

            print(user)
            if not user:
                return  HttpResponseRedirect('/admin/')
            elif admin_conector.is_admin(user):

                print("\n\nadmin\n\n")

                log_conector.add_log(user['id'], 'log in')
                response = HttpResponseRedirect('/admin/user/')
                request.session.set_expiry(None)
                request.session['admin_user_id'] = user['id']
                return response
        response = HttpResponseRedirect('/admin/')
        return response


def logout(request):
    response = HttpResponseRedirect('/admin/')
    try:
        user_id = request.session['admin_user_id']
        user = user_db_conect.get_user_by_id(user_id)
        del request.session['admin_user_id']
        log_conector.add_log(user['id'], 'log out')
    except KeyError:
        pass
    return response



def page(request):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        admin = user_db_conect.get_user_by_id(admin_id)
        list_user = admin_conector.get_all_users()
        return render(request, 'admin_ac/page.html', {'admin': admin, 'list_user': list_user, })
    else:
        return HttpResponseRedirect('/admin/')


def club(request):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        admin = user_db_conect.get_user_by_id(admin_id)
        clubs = admin_conector.get_all_club()
        return render(request, 'admin_ac/page_club.html', {'admin': admin, 'clubs': clubs, })
    else:
        return HttpResponseRedirect('/admin/')


def match(request):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        admin = user_db_conect.get_user_by_id(admin_id)
        matches = admin_conector.get_all_match()

        for match in matches:
            if match.get('goal1') == None and match.get('goal2') == None :
                match['result'] = 'doesn\'t finish'
            else:
                match['result'] = '{0} : {1}'.format(match['goal1'], match['goal2'])

        return render(request, 'admin_ac/page_match.html', {'admin': admin, 'matches': matches, })
    else:
        return HttpResponseRedirect('/admin/')


def events(request):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        admin = user_db_conect.get_user_by_id(admin_id)
        matches = admin_conector.get_all_match()
        matches_with_events = admin_conector.get_events(matches)
        print(matches)
        return render(request, 'admin_ac/page_events.html', {'admin': admin, 'matches': matches_with_events,})
    else:
        return HttpResponseRedirect('/admin/')


def create_event(request):
    if 'admin_user_id' in request.session:
        if request.method == 'GET':
            form = admin_forms.EventCreate
            return render(request, 'admin_ac/event_create.html', {'form': form, })
        if request.method == 'POST':
            form = admin_forms.EventCreate(request.POST)
            if form.is_valid():
                events = {}
                events['win first'] = form.cleaned_data['coeff_win_first']
                events['draw'] = form.cleaned_data['coeff_draw']
                events['win second'] = form.cleaned_data['coeff_win_second']

                admin_conector.add_events(form.cleaned_data['match_id'],
                                            events)
            return HttpResponseRedirect('/admin/event/')

def deleting_event(request, id=None):
    if 'admin_user_id' in request.session:
        admin_conector.del_events(int(id))
        return HttpResponseRedirect('/admin/event/')


def logs(request):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        admin = user_db_conect.get_user_by_id(admin_id)
        logs = admin_conector.get_all_logs()
        return render(request, 'admin_ac/page_logs.html', {'admin': admin, 'logs': logs, })
    else:
        return HttpResponseRedirect('/admin/')


def user_spec(request, id=1):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        admin = user_db_conect.get_user_by_id(admin_id)
        user = user_db_conect.get_user_by_id(int(id))
        return render(request, 'admin_ac/user_spec.html', {'admin': admin, 'user': user, })


def del_user(request, id=None):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        user_db_conect.del_user_by_id(int(id))
        response = HttpResponseRedirect('/admin/')
        return response


def locks_user(request, id):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        user_db_conect.locks_user_by_id(int(id))
        response = HttpResponseRedirect('/admin/')
        return response


def unlocks_user(request, id):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        user_db_conect.unlocks_user_by_id(int(id))
        response = HttpResponseRedirect('/admin/')
        return response

def create_club(request):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        if request.method == 'POST':
            name = request.POST['name']
            if name == ' ' or name == '':
                return HttpResponse('')
            else:
                admin_conector.create_club(name)
                return HttpResponse('')


def del_club(request, id=None):
    if 'admin_user_id' in request.session:
        admin_id = request.session['admin_user_id']
        admin_conector.del_club(int(id))
        return HttpResponseRedirect('/admin/club/')


def match_create(request):
    if 'admin_user_id' in request.session:
        if request.method == 'GET':
            form  = admin_forms.MatchCreate
            return render(request, 'admin_ac/match_create.html', {'form': form, })
        if request.method == 'POST':
            form = admin_forms.MatchCreate(request.POST)
            if form.is_valid():
                if form.cleaned_data['club_1'] != form.cleaned_data['club_2']:
                    admin_conector.match_create(form.cleaned_data['club_1'],
                                                form.cleaned_data['club_2'],
                                                form.cleaned_data['date'], )
            return HttpResponseRedirect('/admin/match/')

def bet_test(id_match, id_win, cofficient):
    bet_match = admin_conector.get_bet_mtach_by_id_match(id_match, id_win)
    admin_conector.add_wingame(id_win)
    if id_win != False:
        for item in bet_match:
            bet = admin_conector.get_bet_by_id_btm(item[0])
            money = bet[1]*cofficient
            user_db_conect.add_money(bet[3], money)
            log_money.add_log_bet(bet[3], 'win', money, bet[0])

def match_spec(request, id=None):
    if 'admin_user_id' in request.session:
        if request.method == 'GET':
            match = admin_conector.get_match_by_id(int(id))
            form = admin_forms.MatchEdit()
            form.fields['date'].initial = match['match_date']
            print(match)
            form.fields['club_1'].initial = match['club_id_1']
            form.fields['club_2'].initial = match['club_id_2']
            if match['goal_1'] != None and match['goal_2'] != None:
                form.fields['gool_club_1'].initial = match['goal_1']
                form.fields['gool_club_2'].initial = match['goal_2']
            return render(request, 'admin_ac/match_spec.html', {'form': form, 'match': match, })
        if request.method == 'POST':
            form = admin_forms.MatchEdit(request.POST)
            print("\n\nhere\n\n")
            if form.is_valid():
                match = admin_conector.get_match_by_id(int(id))
                # if form.cleaned_data['gool_club_1'] != None and form.cleaned_data['gool_club_2'] != None:
                #     if match[7] == False:
                #         test = True
                #         if form.cleaned_data['gool_club_1']  < form.cleaned_data['gool_club_2']:
                #             bet_test(match[0], match[2], match[6])
                #             admin_conector.add_game(form.cleaned_data['club_1'])
                #             admin_conector.add_game(form.cleaned_data['club_2'])
                #         elif  form.cleaned_data['gool_club_1']  > form.cleaned_data['gool_club_2']:
                #             bet_test(match[0], match[1], match[6])
                #             admin_conector.add_game(form.cleaned_data['club_1'])
                #             admin_conector.add_game(form.cleaned_data['club_2'])
                #         else:
                #             bet_test(match[0], False, match[6])
                #             admin_conector.add_game(form.cleaned_data['club_1'])
                #             admin_conector.add_game(form.cleaned_data['club_2'])
                #     else:
                #         test = True
                # else:
                #     test = False

lab/admin_ac/templates/admin_ac/bets.html
{% extends 'admin_ac/page.html' %}

{% block content1 %}
<div class="list_nav">
  <ul class="nav nav-tabs">
    <li >
      <a href="/admin/user/">Users</a>
    </li>
    <li >
      <a href="/admin/club/">Clubs</a>
    </li>
    <li>
      <a href="/admin/match/">Match</a>
    </li>
    <li>
      <a href="/admin/logs/">Logs</a>
    </li>
    <li class="active " >
      <a href="/admin/bets/">Bets</a>
    </li>
    </ul>
</div>
<div class="obj_content">
  <div class="obj_content1">
    <table class="table">
      <thead>
        <tr class="w_text">
          <th>
            #
          </th>
          <th>
            username
          </th>
          <th>
            match
          </th>
          <th>
            money
          </th>
          <th>
            date
          </th>
        </tr>
      </thead>
      <tbody class="bord1">
        {% for item in bets %}
          <tr class="w_text">
            <th scope="row">
              {{ item.4 }}
            </th>
              <td>
                {{ item.5 }}
              </td>
              <td>
                {{ item.8 }}:{{item.9}}
              </td>
              <td>
                {{ item.7 }}
              </td>
              <td>
                {{ item.3 }}
              </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="obj_content2">
    <form class="" action="/admin/bets/" method="post">{% csrf_token %}
      <h3 class="text">Filter</h3>
      {{form.as_p}}
      <button type="sybmit" name="button" class="btn btn-primary">to find</button>
    </form>
  </div>

  <script>
    $(function(){
      $('#id_date').datepicker();
      $('#id_date_max').datepicker();
    });
  </script>
</div>
{% endblock %}

lab/admin_ac/templates/admin_ac/event_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block login %}
<a href="/admin/">
  <img class="admin_img" src="{% static '../static/img/king1.png' %}" alt="" />
</a>
<a href="/admin/logout/">
  <button class="btn btn-primary btn_login btn_logout" type="button" name="button">Log Out</button>
</a>
{% endblock %}

{% block content %}

  <form class="form_create" action="/admin/event/create/" method="post">
    {% csrf_token %}
    <h2 class="title_c">Events create</h2>
      {{form.as_p}}
      <button class="btn btn-primary" type="submit" name="button">Create</button>
  </form>
  <script>
    $(function(){
      $('#id_date').datepicker();
    });
  </script>
{% endblock %}

lab/admin_ac/templates/admin_ac/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<p class="text_login">
  Слава админу
</p>
 <form  class="sign_log_form" action="/admin/" method="post">
   {% csrf_token %}
   {{form.as_p}}
   <input class="btn btn-primary" type="submit" name="name" value="Log in">
 </form>
 <a href="/accaunt/signup/"></a>
{% endblock %}

lab/admin_ac/templates/admin_ac/match_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block login %}
<a href="/admin/">
  <img class="admin_img" src="{% static '../static/img/king1.png' %}" alt="" />
</a>
<a href="/admin/logout/">
  <button class="btn btn-primary btn_login btn_logout" type="button" name="button">Log Out</button>
</a>
{% endblock %}

{% block content %}

  <form class="form_create" action="/admin/match_create/" method="post">{% csrf_token %}
    <h2 class="title_c">Match create</h2>
      {{form.as_p}}
      <button class="btn btn-primary" type="submit" name="button">Create</button>
  </form>
  <script>
    $(function(){
      $('#id_date').datepicker();
    });
  </script>
{% endblock %}

lab/admin_ac/templates/admin_ac/match_spec.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block login %}
<a href="/admin/">
  <img class="admin_img" src="{% static '../static/img/king1.png' %}" alt="" />
</a>
<a href="/admin/logout/">
  <button class="btn btn-primary btn_login btn_logout" type="button" name="button">Log Out</button>
</a>
{% endblock %}
{% block content %}

<!-- <p style="color: green">{{match.id_match}}</p> -->

 <form class="form_create1" action="/admin/match_spec/{{match.id_match}}" method="post">{% csrf_token %}
   <h2 class="title_c t_m" >Edit match</h2>
   <div class="formmatch1">
     {{form.as_p}}
   </div>
   <button class="btn btn-primary btn_sv" type="submit" name="button">Save</button>
 </form>

{% endblock %}

lab/admin_ac/templates/admin_ac/page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block login %}
<a href="/admin/">
  <img class="admin_img" src="{% static '../static/img/king1.png' %}" alt="" />
</a>
<a href="/admin/logout/">
  <button class="btn btn-primary btn_login btn_logout" type="button" name="button">Log Out</button>
</a>
{% endblock %}

{% block content %}
{% if admin %}
<h1 class = "text">{{admin.first_name}} {{admin.last_name}} ({{admin.username}}) </h1>
    <div class="list_nav">
    <ul class="nav nav-tabs">
        <li>
            <a href="/admin/user/">Users</a>
        </li>
        <li>
            <a href="/admin/club/">Clubs</a>
        </li>
        <li>
            <a href="/admin/match/">Match</a>
        </li>
        <li>
            <a href="/admin/event/">Events</a>
        </li>
        <li>
            <a href="/admin/bets/">Bets</a>
        </li>
        <li>
            <a href="/admin/logs/">Logs</a>
        </li>
        </ul>
    </div>

  {% block content_admin %}
  <div class="obj_content">
    <table class="table">
      <thead>
        <tr class="w_text">
          <th>
            #
          </th>
          <th>
            First Name
          </th>
          <th>
            Last Name
          </th>
          <th>
            Username
          </th>
          <th>
            Cash
          </th>
        </tr>
      </thead>
      <tbody class="bord">
      {% for item in list_user %}
      <tr class="w_text">
        <th scope="row">
        <a href="/admin/userprop/{{item.id}}"> {{item.id}}</a>
        </th>
        <td>
          {{item.first_name}}
        </td>
        <td>
          {{item.last_name}}
        </td>
        <td>
          {{item.username}}
        </td>
        <td>
          {{item.money}}
        </td>
          </tr>
          </a>
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% endblock %}
  {% else %}

  <img src="{% static '../static/img/anonym.png' %}" class="img-circle" id="imgan" alt="" />
{% endif %}
{% endblock %}

lab/admin_ac/templates/admin_ac/page_club.html
{% extends 'admin_ac/page.html' %}

{% block content_admin %}
<div class="obj_content">
  <div class="obj_content1">
    <table class="table">
      <thead>
        <tr class="w_text">
          <th>
            #
          </th>
          <th>
            club
          </th>
          <th>
            count
          </th>
        </tr>
      </thead>
      <tbody class="bord ">
        {% for item in clubs %}
        <tr class="w_text">
          <th scope="row">
            {{item.0}}
          </th>
          <td>
            {{item.1}}
          </td>
          <td>
            {{item.3}}
          </td>
          <td>
            <a  class="a_poss" href="/admin/del_club/{{item.0}}"><i class="icon-remove icon-white "></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
  <div class="obj_content2">
          <button id="click_me" class="button_add" type="button" name="button">
            <i class="icon-plus btn_i"> </i>
          </button>
    </div>
        <div id="popup" class="popup"  >
          <h2 class="popup_title" > Add club</h2>
          <form class="" id="form_club"  >{% csrf_token %}
            <input class="in_club" id="name" type="text" name="name" value=""><br>
            <button id="create" class="btn_club" type="submit" name="button">create</button>
          </form>
            <div id="btn_close" class="btn_close"><i class="icon-remove icon-white"></i></div>
          </div>

          <script >
          $(document).on('submit', '#form_club', function(e){
            e.preventDefault();
            $.ajax({
              type:'POST',
              url:'/admin/create_club/',
              data: {
                name:$('#name').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
              },
              success:function(){
                $('#name').val('');
              }
            });
          });

          $(function() {
            $('#popup').hide();
            $('#hide_layout').hide()
            $('#hide_layout').css({opacity: .5});

            alignCenter($('#popup'));

            $(window).resize(function(){
              alignCenter($('#popup'));
            })
            $('#create').click(function() {

            })

            $('#click_me').click(function(){
              $('#hide_layout, #popup').fadeIn(300);
            })

            $('#btn_close, #hide_layout').click(function(){
              $('#hide_layout, #popup').fadeOut(300);
            })


            function alignCenter(elem) {
              elem.css({
                left: ($(window).width() - elem.width() - 800) / 2 + 'px',
                top: ($(window).height() - elem.height()) / 2 + 'px'
              })
            }
          })
          </script>

          <div id="hide_layout" class="hide_layout" ></div>

</div>
{% endblock %}

lab/admin_ac/templates/admin_ac/page_events.html
{% extends 'admin_ac/page.html' %}

{% block content_admin %}
<div class="obj_content">
    <table class="table">
      <thead>
        <tr class="w_text">
            <th>
                #
            </th>
            <th>
                match
            </th>
            <th>
                date
            </th>
            <th>
                events
            </th>
            <th>
                
            </th>
        </tr>
      </thead>
      <tbody class="bord1">
        {% for item in matches %}
          <tr class="w_text">
            <th scope="row">
              {{ item.id_match }}
            </th>
              <td>
                {{ item.name_club1 }} - {{ item.name_club2 }}
              </td>
              <td>
                {{ item.date_match }}
              </td>
              <td>
                {% for event in item.events %}
                    <p>{{ event.name_event }}: {{ event.coefficient }} <p>
                {% endfor %}
              </td>
                <td>
                    <a class="a_poss" href="/admin/event/del_event/{{ item.id_match }}"><i class="icon-remove icon-white"></i></a>
                </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="obj_content2">
    <a href="/admin/event/create">
      <button id="click_me" class="button_add" type="button" name="button">
        <i class="icon-plus btn_i"> </i>
      </button>
    </a>
  </div>
</div>

{% endblock %}

lab/admin_ac/templates/admin_ac/page_logs.html
{% extends 'admin_ac/page.html' %}

{% block content_admin %}
<div class="obj_content">
    <table class="table">
      <thead>
        <tr class="w_text">
          <th>
            #
          </th>
          <th>
            username
          </th>
          <th>
            action
          </th>
          <th>
            date
          </th>
        </tr>
      </thead>
      <tbody class="bord1">
        {% for item in logs %}
          <tr class="w_text">
            <th scope="row">
              {{ item.0 }}
            </th>
              <td>
                {{ item.1 }}
              </td>
              <td>
                {{ item.2 }}
              </td>
              <td>
                {{ item.3 }}
              </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

{% endblock %}

lab/admin_ac/templates/admin_ac/page_match.html
{% extends 'admin_ac/page.html' %}

{% block content_admin %}
<div class="obj_content">
  <div class="obj_content1">
    <table class="table">
        <thead>
          <tr class="w_text">
            <th>
              #
            </th>
            <th>
              club_1
            </th>
            <th>
              club_2
            </th>
            <th>
              date
            </th>
            <th>
              result
            </th>
          </tr>
        </thead>
        <tbody class="bord1">
          {% for item in matches %}
            <tr class="w_text">
              <th scope="row">
              <a href="/admin/match_spec/{{item.id_match}}">{{ item.id_match }}</a>
              </th>
                <td>
                    {{ item.name_club1 }}
                </td>
                <td>
                    {{ item.name_club2 }}
                </td>
                <td>
                    {{ item.match_date }}
                </td>
                <td>
                    {{ item.result }}
                </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
  <div class="obj_content2">
    <a href="/admin/match_create/">
      <button id="click_me" class="button_add" type="button" name="button">
        <i class="icon-plus btn_i"> </i>
      </button>
    </a>
  </div>
</div>
{% endblock %}

lab/admin_ac/templates/admin_ac/user_spec.html
  {% extends 'base.html' %}
{% load staticfiles %}

{% block login %}
<a href="/admin/">
  <img class="admin_img" src="{% static '../static/img/king1.png' %}" alt="" />
</a>
<a href="/admin/logout/">
  <button class="btn btn-primary btn_login btn_logout" type="button" name="button">Log Out</button>
</a>
{% endblock %}

{% block content %}
{% if user %}
<h1 class = "text">{{user.first_name}} {{user.last_name}} ({{user.username}}) </h1>
{% if user.is_activ != False %}
<a href="/admin/locks/user/{{user.id}}" class="a_loc">
  <button class="button_add loc_pos" type="button" name="button">Locks</button>
</a>
{% else %}
<a href="/admin/unlocks/user/{{user.id}}" class="a_loc">
  <button class="button_add loc_pos" type="button" name="button">UnLocks</button>
</a>
{% endif %}
<a href="/admin/del/user/{{user.id}}/">
  <button class="button_add del_pos" type="button" name="button">Delit</button>
</a>
<p class="text txt_cash">
  cash {{user.money}} $
  </p>
  {% else %}

  <img src="{% static '../static/img/anonym.png' %}" class="img-circle" id="imgan" alt="" />
{% endif %}
{% endblock %}